# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      super_hero_api_key: ${{secrets.SUPER_HERO_API_KEY}}
      auth0_client_id: ${{secrets.AUTH0_CLIENT_ID}}
      auth0_client_secret: ${{secrets.AUTH0_CLIENT_SECRET}}
      auth0_audience: ${{secrets.AUTH0_AUDIENCE}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
    - uses: codecov/codecov-action@v1
      with:
        file: ./**/jacocoXml
        name: codecov
