name: deploy to production

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      run: |
          tee tacs-2021-v3.pem <<< "${{secrets.PEM}}"
          ssh -t -t -i "tacs-2021-v3.pem" ec2-user@ec2-52-35-83-13.us-west-2.compute.amazonaws.com
          ls
